import { Pipe, PipeTransform } from '@angular/core';

@Pipe({
  name: 'translateTemp',
})
export class TranslateTempPipe implements PipeTransform {
  transform(temperament: string): string {

    const temperamentTranslations: { [key: string]: string } = {
      Stubborn: 'Terco',
      Curious: 'Curioso',
      Playful: 'Juguetón',
      Adventurous: 'Aventurero',
      Active: 'Activo',
      'Fun-loving': 'Amante de la diversión',
      Aloof: 'Distante',
      Clownish: 'Payaso',
      Dignified: 'Digno',
      Independent: 'Independiente',
      Happy: 'Feliz',
      Wild: 'Salvaje',
      Hardworking: 'Trabajador',
      Dutiful: 'Cumplidor',
      Outgoing: 'Extrovertido',
      Friendly: 'Amigable',
      Alert: 'Alerta',
      Confident: 'Confiado',
      Intelligent: 'Inteligente',
      Courageous: 'Corajudo',
      Loyal: 'Leal',
      Brave: 'Valiente',
      Docile: 'Dócil',
      Responsive: 'Responsivo',
      Composed: 'Compuesto',
      Receptive: 'Receptivo',
      Faithful: 'Fiel',
      Loving: 'Amoroso',
      Protective: 'Protector',
      Trainable: 'Entrenable',
      Responsible: 'Responsable',
      Energetic: 'Energético',
      Gentle: 'Suave',
      Dominant: 'Dominante',
      'Strong Willed': 'Voluntarioso',
      Affectionate: 'Cariñoso',
      Obedient: 'Obediente',
      Assertive: 'Asertivo',
      Devoted: 'Devoto',
      Reserved: 'Reservado',
      Calm: "Tranquilo",
      Tenacious: "Tenaz",
      Eager: "Ansioso",
      'Good-natured': "De buen carácter",
      'Even Tempered': "De temperamento uniforme",
      Spirited: "Animado",
      Companionable: "Sociable",
      "Self-assured": "Seguro de sí mismo",
      Fearless: "Sin miedo",
      Steady: "Constante",
      Bold: "Audaz",
      Proud: "Orgulloso",
      "Sweet-Tempered": "De buen temperamento",
      Sensitive: "Sensible",
      Watchful: "Vigilante",
      Agile: "Ágil",
      Trusting: "Confiable",
      Attentive: "Atento",
      Rugged: "Robusto",
      Fierce: "Feroz",
      Refined: "Refinado",
      Excitable: "Excitado",
      Determined: "Determinado",
      Kind: "Amable",
      Reliable: "De confianza",
      Territorial: "Territorial",
      Relaxed: "Relajado",
      Social: 'Social',
      Interactive: 'Interactivo',
      Lively: 'Vivaz',
      'Easy Going': 'De fácil trato',
      Demanding: 'Exigente',
      Dependent: 'Dependiente'
    };

    return temperamentTranslations[temperament] || temperament;
  }
}
